# SSE Client Configuration
# This file contains default model configurations for all providers

# Default settings
timeout: 30
max_tokens: 4096
temperature: 0.7
default_provider: "bailian"
default_model: "qwen-max"

# Provider configurations
providers:
  bailian:
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
    api_key: "your-bailian-api-key"
    models:
      - "qwen-max"
      - "qwen-plus"
      - "qwen-turbo"
      - "qwen-long"
      - "qwen2.5-72b-instruct"
      - "qwen2.5-32b-instruct"
      - "qwen2.5-14b-instruct"
      - "qwen2.5-7b-instruct"
      - "qwen2.5-3b-instruct"
      - "qwen2.5-1.5b-instruct"
      - "qwen2.5-0.5b-instruct"
      - "qwen2.5-coder-32b-instruct"
      - "qwen2.5-coder-14b-instruct"
      - "qwen2.5-coder-7b-instruct"
      - "qwen2.5-coder-3b-instruct"
      - "qwen2.5-coder-1.5b-instruct"
      - "qwen2.5-math-72b-instruct"
      - "qwen2.5-math-32b-instruct"
      - "qwen2.5-math-14b-instruct"
      - "qwen2.5-math-7b-instruct"
      - "qwen2-vl-72b-instruct"
      - "qwen2-vl-7b-instruct"
      - "qwen-vl-max"
      - "qwen-vl-plus"
      - "qwen-custom"
      - "test-model-bailian"

  openai:
    base_url: "https://api.openai.com/v1/chat/completions"
    api_key: "your-openai-api-key"
    models:
      - "gpt-5"
      - "gpt-4o"
      - "gpt-4o-mini"
      - "gpt-4"
      - "gpt-3.5-turbo"
      - "gpt-3.5-turbo-16k"
      - "o1-preview"
      - "o1-mini"
      - "my-custom-gpt"
      - "my-company-model"
      - "test-model-openai"

  google:
    base_url: "https://generativelanguage.googleapis.com/v1beta/models"
    api_key: "your-google-api-key"
    models:
      - "gemini-2.5-flash"
      - "gemini-1.5-flash"
      - "gemini-2.5-pro"
      - "gemini-1.5-pro"
      - "gemini-2.0-flash-exp"
      - "test-model-google"

  anthropic:
    base_url: "https://api.anthropic.com/v1/messages"
    api_key: "your-anthropic-api-key"
    models:
      - "claude-sonnet-4-20250514"
      - "claude-3-7-sonnet-20250219"
      - "claude-3-5-sonnet-20241022"
      - "claude-3-5-haiku-20241022"
      - "claude-3-opus-20240229"
      - "test-model-anthropic"

  deepseek:
    base_url: "https://api.siliconflow.cn/v1"
    api_key: "your-deepseek-api-key"
    models:
      - "deepseek-v3.1"
      - "deepseek-r1"
      - "deepseek-r1-0528"
      - "deepseek-v3"
      - "deepseek-ai/DeepSeek-V3.1"
      - "test-model-deepseek"
      - "deepseek-v3-latest"